"""add shopping_list_item

Revision ID: 20260426012636
Revises: 20260426012619
Create Date: 2026-04-26 01:26:37.957287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20260426012636'
down_revision: Union[str, None] = '20260426012619'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shopping_list_item',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('ingredient_id', sa.UUID(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('source_plan_id', sa.UUID(), nullable=True),
    sa.Column('is_purchased', sa.Boolean(), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], name=op.f('fk_shopping_list_item_ingredient_id_ingredient')),
    sa.ForeignKeyConstraint(['source_plan_id'], ['plan.id'], name=op.f('fk_shopping_list_item_source_plan_id_plan')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shopping_list_item'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shopping_list_item')
    # ### end Alembic commands ###
