"""add food_inventory and dish_inventory

Revision ID: 20260426012648
Revises: 20260426012636
Create Date: 2026-04-26 01:26:49.694987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20260426012648'
down_revision: Union[str, None] = '20260426012636'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dish_inventory',
    sa.Column('recipe_id', sa.UUID(), nullable=False),
    sa.Column('recipe_name_snapshot', sa.String(), nullable=False),
    sa.Column('servings_remaining', sa.Integer(), nullable=False),
    sa.Column('location', sa.Enum('fridge', 'freezer', name='dishlocation'), nullable=False),
    sa.Column('cooked_at', sa.DateTime(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], name=op.f('fk_dish_inventory_recipe_id_recipe')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dish_inventory'))
    )
    op.create_table('food_inventory',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('ingredient_id', sa.UUID(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], name=op.f('fk_food_inventory_ingredient_id_ingredient')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_food_inventory'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('food_inventory')
    op.drop_table('dish_inventory')
    # ### end Alembic commands ###
