"""add recipe_ingredient and recipe_tag

Revision ID: 20260426012515
Revises: 20260426011955
Create Date: 2026-04-26 01:25:16.562136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20260426012515'
down_revision: Union[str, None] = '20260426011955'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipe_ingredient',
    sa.Column('recipe_id', sa.UUID(), nullable=False),
    sa.Column('ingredient_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], name=op.f('fk_recipe_ingredient_ingredient_id_ingredient')),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], name=op.f('fk_recipe_ingredient_recipe_id_recipe')),
    sa.PrimaryKeyConstraint('recipe_id', 'ingredient_id', name=op.f('pk_recipe_ingredient'))
    )
    op.create_table('recipe_tag',
    sa.Column('recipe_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], name=op.f('fk_recipe_tag_recipe_id_recipe')),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], name=op.f('fk_recipe_tag_tag_id_tag')),
    sa.PrimaryKeyConstraint('recipe_id', 'tag_id', name=op.f('pk_recipe_tag'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipe_tag')
    op.drop_table('recipe_ingredient')
    # ### end Alembic commands ###
