"""dish_inventory_recipe_id_nullable

Revision ID: 20260426210018
Revises: 20260426012659
Create Date: 2026-04-26 21:00:19.333067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20260426210018'
down_revision: Union[str, None] = '20260426012659'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dish_inventory', 'recipe_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dish_inventory', 'recipe_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
