"""add meal_slot

Revision ID: 20260426012619
Revises: 20260426012540
Create Date: 2026-04-26 01:26:19.807621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20260426012619'
down_revision: Union[str, None] = '20260426012540'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meal_slot',
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('slot_label', sa.String(), nullable=False),
    sa.Column('recipe_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('empty', 'planned', 'eaten', 'skipped', name='mealslotstatus'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plan.id'], name=op.f('fk_meal_slot_plan_id_plan')),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], name=op.f('fk_meal_slot_recipe_id_recipe')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meal_slot'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meal_slot')
    # ### end Alembic commands ###
