"""add recipe

Revision ID: 20260426011955
Revises: 2b07a8d6a13e
Create Date: 2026-04-26 01:19:56.227880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20260426011955'
down_revision: Union[str, None] = '2b07a8d6a13e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipe',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('servings_produced', sa.Integer(), nullable=False),
    sa.Column('days_fridge', sa.Integer(), nullable=False),
    sa.Column('days_freezer', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recipe')),
    sa.UniqueConstraint('name', name=op.f('uq_recipe_name'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipe')
    # ### end Alembic commands ###
